### PR TITLE
GCC2017 hackathon work

### PR DESCRIPTION
**Pull request by dannon**
Awesome stuff @eggzilla, @bernt-matthias, @bebatut!  I'm hoping to merge in my dom-path-distillation work later today.

### CODE REVIEW

**Comment by willdurand** [comment]
Hi @dannon, last night I hacked on a parallel implementation, it is now feature complete and it is able to record/replay almost any tours. I have written a DOM path algo to get a minimal unique DOM path. I have also mimicked what Galaxy does in term of YAML processing (both in Python and JS).

I have done that to help @bebatut et al. and also because I had some spare time. My company gave me a full day to work on it today. It should be open sourced soon, test coverage is too low right now (but not null :wink:).

**Comment by willdurand** [comment]
Last but not least, it should be cross-browser (Chrome, Opera & Firefox) but it has only been tested on Chrome so far.

**Comment by dannon** [comment]
@willdurand Ahh, ok.  I was just fixing up my local minimal dom path stuff, here.  Can we PR yours here and merge it in to keep the record of folks who'd worked on it, or do you wan to chuck this stuff and use yours?

**Comment by willdurand** [comment]
I thought a lot about starting from this repo to be honest but I used a boilerplate to get started with cross-browser + ES6 + live reload + ... That was much easier to start from the boilerplate.

Since it is not based on jQuery anymore, I did not reuse much of the code, except what I have done last year more or less. However, all contributors on this repo have their names in the README already.

**Comment by dannon** [comment]
Is this something you want to keep private in your account, or upstream it to the community?  If we're going to put it into the main galaxyproject community account (so, galaxyproject/tourbuilder, which was the intent with this repo), I'd like to merge it all, still.

**Comment by willdurand** [comment]
This should be opensourced this week I guess. I do not have any interest in keeping things private, I am not a Galaxy user either BTW.

Just trying to help there...

**Comment by dannon** [comment]
Sure, I appreciate it!  Just trying to make sure it's something the community can all work together on.  If you don't want to merge it here, what we can do is just opensource it how you'd like and I can (well, depending on license I guess), merge and create a galaxyproject/tourbuilder fork using what you've done as a base.

**Pull request merged**
